const COURSES = [
    {
        id: 'html', name: 'HTML', icon: 'H', level: 'مبتدئ', color: 'html', description: 'ابنِ هيكل صفحات الويب الدلالي من أول سطر وحتى صفحة شخصية كاملة.', duration: '4 أسابيع', projects: ['صفحة شخصية'], lessons: [
            { id: 'html-what', title: 'ما هي HTML؟', duration: '08:00', description: 'HTML هي لغة الترميز التي تصف هيكل محتوى صفحات الويب.', content: 'تخيل صفحة الويب كهيكل مبنى: HTML تحدد الغرف والأبواب والعناوين. المتصفح يقرأ العناصر ويحوّلها إلى واجهة يمكن للمستخدم رؤيتها.', code: '<!doctype html>\n<html lang="ar">\n  <body>\n    <h1>مرحبًا بك في الويب</h1>\n  </body>\n</html>', examples: ['استخدم h1 للعنوان الرئيسي مرة واحدة.', 'اجعل اللغة lang="ar" عندما يكون المحتوى عربيًا.'], notes: ['HTML لا تنفذ المنطق البرمجي، بل تصف المحتوى.', 'العناصر الدلالية تجعل الصفحة أوضح لمحركات البحث وقارئات الشاشة.'], mistakes: ['نسيان إغلاق العناصر المتداخلة.', 'استخدام div لكل شيء بدل العناصر الدلالية.'], exercise: 'أنشئ صفحة فيها عنوان رئيسي وفقرة تعريفية عنك.', questions: [{ q: 'ما الوظيفة الأساسية لـ HTML؟', options: ['تنسيق الألوان', 'وصف هيكل المحتوى', 'تشغيل الخادم', 'إدارة قاعدة البيانات'], answer: 1 }] },
            { id: 'html-structure', title: 'بنية مستند HTML', duration: '12:00', description: 'تعلم DOCTYPE وhtml وhead وbody ولماذا لكل جزء مكانه.', content: 'كل مستند HTML حديث يبدأ بإعلان نوع المستند، ثم عنصر html الذي يحتوي head للمعلومات الوصفية وbody للمحتوى الظاهر.', code: '<!doctype html>\n<html lang="ar" dir="rtl">\n<head>\n  <meta charset="UTF-8">\n  <title>صفحتي</title>\n</head>\n<body>\n  <p>المحتوى هنا</p>\n</body>\n</html>', examples: ['ضع title داخل head.', 'ضع النصوص والصور التي يراها الزائر داخل body.'], notes: ['charset يمنع مشاكل عرض الحروف العربية.'], mistakes: ['وضع عناصر مرئية داخل head.'], exercise: 'اكتب الهيكل الكامل لصفحة عربية بعنوان مناسب.', questions: [{ q: 'أين يوضع عنوان الصفحة في التبويب؟', options: ['body', 'footer', 'title داخل head', 'main'], answer: 2 }] },
            { id: 'html-elements', title: 'العناوين والفقرات والروابط', duration: '15:00', description: 'استخدم عناصر النص الأساسية وأنشئ روابط صالحة بين الصفحات.', content: 'العناوين من h1 إلى h6 تعبّر عن التسلسل، وp للفقرات، وa للروابط. قيمة href تحدد وجهة الرابط.', code: '<h1>ملفي التعليمي</h1>\n<h2>نبذة</h2>\n<p>أتعلم بناء واجهات مفيدة.</p>\n<a href="courses.html">استكشف الكورسات</a>', examples: ['اكتب نص الرابط ليصف وجهته.', 'استخدم href نسبيًا للصفحات داخل المشروع.'], notes: ['ترتيب العناوين مهم لإمكانية الوصول.'], mistakes: ['رابط بلا href أو نص غير مفهوم.'], exercise: 'أنشئ قسمًا فيه عنوان وفر paragraph ورابط إلى courses.html.', questions: [{ q: 'ما العنصر المستخدم لإنشاء رابط؟', options: ['img', 'a', 'link', 'href'], answer: 1 }] },
            { id: 'html-forms', title: 'النماذج وحقول الإدخال', duration: '18:00', description: 'صمم نموذج تواصل واضحًا باستخدام label وinput وbutton.', content: 'النماذج تجمع مدخلات المستخدم. اربط label بحقل input عبر for وid، وحدد type المناسب لمساعدة المتصفح.', code: '<form>\n  <label for="email">البريد الإلكتروني</label>\n  <input id="email" type="email" required>\n  <button type="submit">إرسال</button>\n</form>', examples: ['required يمنع الإرسال الفارغ.', 'استخدم textarea للنصوص الطويلة.'], notes: ['التحقق في HTML طبقة أولى، وليس بديلًا عن التحقق البرمجي.'], mistakes: ['غياب label أو تكرار id.'], exercise: 'أنشئ نموذجًا للاشتراك باسم وبريد إلكتروني.', questions: [{ q: 'ما أهمية label؟', options: ['تغيير اللون', 'وصف الحقل وربطه به', 'تشغيل JavaScript', 'إخفاء الحقل'], answer: 1 }] },
            { id: 'html-semantic', title: 'HTML الدلالية', duration: '16:00', description: 'نظم الصفحة بعناصر header وnav وmain وsection وfooter.', content: 'العناصر الدلالية تحمل معنى واضحًا بدل الاعتماد على divs مجهولة. هذا يفيد التنظيم والوصول وSEO.', code: '<header>الشعار</header>\n<nav><a href="index.html">الرئيسية</a></nav>\n<main><section><h1>المحتوى</h1></section></main>\n<footer>بيشوي كود</footer>', examples: ['استخدم main مرة واحدة.', 'ضع الروابط الأساسية داخل nav.'], notes: ['الدلالة لا تمنح تنسيقًا تلقائيًا، CSS مسؤولة عن الشكل.'], mistakes: ['استخدام main داخل main.'], exercise: 'حوّل صفحة مبنية على divs إلى بنية دلالية.', questions: [{ q: 'أي عنصر يمثل المحتوى الرئيسي؟', options: ['aside', 'main', 'nav', 'footer'], answer: 1 }] },
            { id: 'html-project', title: 'مشروع: صفحة شخصية', duration: '25:00', description: 'اجمع ما تعلمته لبناء صفحة شخصية منظمة باستخدام HTML فقط.', content: 'ابدأ بهيكل المستند، ثم أضف تعريفًا ومهارات وروابط تواصل. ركز على التسلسل الدلالي والنصوص الواضحة.', code: '<main>\n  <section aria-labelledby="about-title">\n    <h1 id="about-title">بيشوي - مطور واجهات</h1>\n    <p>أبني تجارب ويب عربية سهلة الاستخدام.</p>\n  </section>\n</main>', examples: ['قسّم المحتوى إلى أقسام واضحة.', 'أضف alt وصفيًا عند استخدام الصور.'], notes: ['المشروع هو فرصتك لتجربة تركيب العناصر.'], mistakes: ['القفز من h1 إلى h4 بلا سبب.'], exercise: 'ابنِ صفحة شخصية تحتوي على نبذة ومهارات ومشروعين وطريقة تواصل.', questions: [{ q: 'ما أول عنوان مناسب للصفحة؟', options: ['h6', 'h1', 'p', 'title فقط'], answer: 1 }] }
        ]
    },
    { id: 'css', name: 'CSS', icon: '#', level: 'مبتدئ', color: 'css', description: 'حوّل الهياكل إلى واجهات متجاوبة باستخدام Flexbox وGrid وتقنيات CSS الحديثة.', duration: '6 أسابيع', projects: ['Landing Page', 'Portfolio', 'Dashboard'], lessons: ['Selectors', 'Colors and Fonts', 'Box Model', 'Flexbox', 'CSS Grid', 'Responsive Design', 'Transitions and Variables'].map((title, index) => ({ id: `css-${index + 1}`, title, duration: '20:00', description: `درس عملي في ${title} مع أمثلة قابلة للتطبيق في مشاريع الواجهات.`, content: `في هذا الدرس ندرس ${title} ونربطه بمشكلة حقيقية في تصميم واجهة مستخدم. اكتب المثال ثم غيّر القيم ولاحظ النتيجة.`, code: `.card {\n  display: ${index === 3 ? 'flex' : index === 4 ? 'grid' : 'block'};\n  gap: 16px;\n  padding: 20px;\n  color: #102a43;\n}`, examples: ['ابدأ بتنسيق بسيط ثم أضف التحسينات.', 'اختبر التصميم على عرض ضيق.'], notes: ['تسمية الأصناف الواضحة تقلل الفوضى.'], mistakes: ['الاعتماد على position بدل layout المناسب.'], exercise: `طبّق ${title} على بطاقة كورس صغيرة.`, questions: [{ q: `أي تقنية ترتبط مباشرة بـ ${title}؟`, options: ['CSS', 'HTML فقط', 'SQL', 'DNS'], answer: 0 }] })) },
    { id: 'javascript', name: 'JavaScript', icon: 'JS', level: 'متوسط', color: 'javascript', description: 'أضف المنطق والتفاعل للواجهات من المتغيرات حتى APIs والتطبيقات الكاملة.', duration: '8 أسابيع', projects: ['Calculator', 'To-Do App', 'Quiz App', 'Notes App'], lessons: ['المتغيرات وأنواع البيانات', 'الشروط والحلقات', 'الدوال و Arrow Functions', 'Arrays و Objects', 'DOM واختيار العناصر', 'Events والنماذج', 'LocalStorage و JSON', 'Array Methods', 'Promises و async/await', 'Fetch API', 'Error Handling'].map((title, index) => ({ id: `js-${index + 1}`, title, duration: '24:00', description: `تعلّم ${title} من خلال تجربة صغيرة ومفهوم قابل لإعادة الاستخدام.`, content: `JavaScript تجعل الصفحة تستجيب للمستخدم. في ${title} ستبني جزءًا صغيرًا ثم تربطه بفكرة تطبيقية.`, code: `const lesson = '${title}';\nconsole.log(lesson);\n\nfunction practice(value) {\n  return value + ' - جاهز للتطبيق';\n}`, examples: ['افحص القيم في Console أثناء التعلم.', 'قسّم المشكلة إلى دوال صغيرة.'], notes: ['سمِّ المتغيرات بأسماء تشرح محتواها.'], mistakes: ['تعديل DOM قبل تحميله.', 'نسيان التعامل مع الأخطاء.'], exercise: `اكتب تجربة قصيرة تطبق ${title}.`, questions: [{ q: `ما اللغة التي تمنح الصفحة تفاعلًا في درس ${title}؟`, options: ['CSS', 'JavaScript', 'HTML', 'SVG'], answer: 1 }] })) },
    { id: 'python', name: 'Python', icon: 'Py', level: 'مبتدئ', color: 'python', description: 'ابدأ البرمجة بلغة واضحة وتعلم البيانات والدوال والبرمجة الكائنية.', duration: '6 أسابيع', projects: ['Calculator', 'Guessing Game', 'Student Management'], lessons: ['أول برنامج', 'المتغيرات وأنواع البيانات', 'Lists و Dictionaries', 'الشروط والحلقات', 'الدوال والمعاملات', 'Exceptions والملفات', 'Modules و Packages', 'مقدمة OOP', 'Classes و Objects', 'Inheritance'].map((title, index) => ({ id: `py-${index + 1}`, title, duration: '22:00', description: `مقدمة عملية إلى ${title} بلغة Python وبأسلوب يناسب المبتدئين.`, content: `Python تتميز ببساطة صياغتها. في ${title} ستفهم الفكرة ثم تطبقها في مثال صغير قابل للتوسعة.`, code: `def practice(value):\n    return f"{value} - تم التنفيذ"\n\nprint(practice("${title}"))`, examples: ['حافظ على المسافات البادئة.', 'اختبر كل فكرة بتغيير قيمة واحدة.'], notes: ['القراءة الجيدة للكود مهارة أساسية.'], mistakes: ['خلط المسافات البادئة.', 'استخدام اسم متغير غامض.'], exercise: `اكتب برنامجًا صغيرًا يطبق ${title}.`, questions: [{ q: 'أي لغة نستخدم في هذه الوحدة؟', options: ['Python', 'JavaScript', 'CSS', 'HTML'], answer: 0 }] })) }
];
const ALL_LESSONS = COURSES.flatMap(course => course.lessons.map((lesson, index) => ({ ...lesson, courseId: course.id, courseName: course.name, number: index + 1 })));
const ACHIEVEMENTS = [
    { id: 'first-lesson', icon: '🏆', title: 'أول درس', description: 'أكملت أول درس' },
    { id: 'ten-lessons', icon: '🚀', title: 'بداية قوية', description: 'أكملت أول 10 دروس' },
    { id: 'perfect-score', icon: '💯', title: 'نتيجة كاملة', description: 'حصلت على 100% في اختبار' },
    { id: 'html-master', icon: 'H', title: 'HTML Master', description: 'أكملت كورس HTML' },
    { id: 'css-master', icon: '#', title: 'CSS Master', description: 'أكملت كورس CSS' },
    { id: 'javascript-master', icon: 'JS', title: 'JavaScript Master', description: 'أكملت كورس JavaScript' },
    { id: 'python-master', icon: 'Py', title: 'Python Master', description: 'أكملت كورس Python' }
];
